/* Q1) What is the total revenue generated so far by the respective store through zomato? */

select sum(s.qty * p.price_i) as total_revenue 
from sales as s 
join products as p 
on 
   s.products_id = p.products_id;

/* Q2) What is the total revenue generated by top 5 customers and also show their membership status as 'Gold' Or "Regular' respectively. */ 
select * from products

select a.user_id,sum(a.qty * p.price_i) as revenue,
case
    when a.user_id in (select g.user_id from gold_users as g) 
	then 'gold'
    else 'Regular'
end as status
from sales as a 
join users as u 
on a.user_id = u.user_id 
join products as p 
on a.products_id=p.products_id
group by 1 order by 2 desc 
limit 5;

/* Q3) Show the top 5 most popular products & bottom 5 products as per their demands respectively. */


(select p.products_id,p.product_name,count(p.products_id) as repeated_products,'top 5' tag
from sales as s 
join products as p 
on 
   s.products_id = p.products_id
group by 1,2
order by 3 desc
limit 5
)

union
(select p.products_id,p.product_name,count(p.products_id) as repeated_products,'bottom 5' tag
from sales as s 
join products as p 
on 
   s.products_id = p.products_id
group by 1,2
order by 3 asc
limit 5
);

/* Q4) Identify products that are low in demand and requires promotional offers/ */


select p.products_id,p.product_name,count(p.products_id) as repeated_products
from sales as s 
join products as p 
on 
   s.products_id = p.products_id
group by 1,2
order by 3 asc
limit 5;


/* Q5) How many days have each customers visited zomato to order from the respective store? */

select * from sales

select 
      user_id,
	  count(distinct order_date) as visit  
from sales 
group by user_id 
order by visit desc;


/* Q6) What was the first product purchased by the top 5 customers through zomato? */


select * from products


with cte_table as 
(
      select s.user_id as user_id,
             sum(s.qty * p.price_i) as total_amount 
      from sales as s 
      join products as p 
        on s.products_id = p.products_id 
	  group by 1
	  order by 2 desc 
	  limit 5
)


select * from (
select s.user_id,
       s.order_date,
	   p.product_name,
	   row_number() over(
	          PARTITION by s.user_id 
			  order by s.order_date asc
			  ) as rnk 
from sales as s 
join products as p 
   on s.products_id=p.products_id 
where s.user_id in (
    select user_id from cte_table
	) 
) b 
where rnk=1;

/* Q7) Which products are likely to be the first pick for new customers on zomato? */

with cte_table as (
select * ,row_number() over(
                 partition by user_id 
                 order by order_date asc 
                ) as rnk 
		from sales)


select products_id,
       count(products_id) as repated_first_order 
from cte_table 
where rnk<=1 
group by 1 
order by 2 desc;

/* Q8) What is the most purchased item on menu and how many times it was purchased by all customers? */
select * from sales
select s.products_id,p.product_name,count(s.products_id) as total_no_of_sales from sales as s join products as p on
s.products_id = p.products_id
group by 1,2 order by 2 desc;


/* Q9) Which is the most purchased item on menu and how many times was it purchased by individual customers? */
with cte_table as (
select products_id,
       count(products_id) as total_count 
from sales 
GROUP by 1 
order by 2 
desc limit 1
)

select user_id ,
       products_id,
	   count(products_id) as total_no 
from sales 
where products_id in (
        select products_id from cte_table
		) 
group by 1,2 
order by 3 desc;


/* Q10) Which item was most popular for each customer? */
select * from sales where user_id=6
select * from (
select user_id,
       products_id,
	   count(products_id),
	   row_number() over(
	                 partition by user_id 
					 order by 2 asc
					 ) as rnk
from sales as s 
group by 1,2 
order by 3 desc
) t 
where rnk<=1 
order by 1 ;

/* Q11) Which item was first purchased by a regular member after they became a gold member? */

select * from gold_users
select * from sales where user_id =6

select * from (
select g.user_id,
       s.products_id,
	   s.order_date,
	   g.gold_signup_date,
	   count(s.products_id),
	   row_number() over(
	               partition by g.user_id 
				   order by s.order_date asc
				   ) as rnk
from gold_users as g 
join sales as s 
     on g.user_id = s.user_id 
where  g.gold_signup_date <= s.order_date
group by 1,2,3,4 
order by 4 desc
)t 
where rnk<=1;

-- Alternative way without group by 
select * from (
select g.user_id,
       s.products_id,
	   s.order_date,
	   g.gold_signup_date,
	   row_number() over(
	               partition by g.user_id 
				   order by s.order_date asc
				   ) as rnk
from gold_users as g 
join sales as s 
     on g.user_id = s.user_id 
where  g.gold_signup_date <= s.order_date
)t 
where rnk<=1
order by 1;

/* Q12) Which item was purchased just before a regular member became a gold member? */


select * from (
select g.user_id,
       s.products_id,
	   s.order_date,
	   g.gold_signup_date,
	   row_number() over(
	               partition by g.user_id 
				   order by s.order_date desc
				   ) as rnk
from gold_users as g 
join sales as s 
     on g.user_id = s.user_id 
where  g.gold_signup_date > s.order_date
)t 
where rnk<=1
order by 1;

/* Q13) What is the total no. of orders and amount spent by each customer before they became a gold member? */

select 
      s.user_id,
	  sum(s.qty * p.price_i) as amount_spend ,
	  count(distinct s.order_id) as orders_purchased 
from sales as s 
join gold_users as  g 
     on s.user_id = g.user_id 
join products as p 
on p.products_id = s.products_id 
where s.order_date < g.gold_signup_date 
group by 1 
order by 2 desc;

/* Q14) Count how many high ticket size orders (i.e qty > 3/order) were placed ? */


select count(*) from sales where qty >=3 ;
select * from products

/* Q15) Consider 10 zomato points = Rs 2
		For	Product: P1 - P6 = 5 points / item
					 P7 - P10 = 10 points / item
					 P11 - P25 = 5 points / item
	Then, Calculate how many zomato points have been collected so far by individual user and 
	for which product maximum zomato points have been rewarded to customers so far. 
*/

create table  zomato_points as 
select s.user_id,p.product_name,sum(s.qty),
case 
    when p.product_name in ('P7', 'P8', 'P9', 'P10') then sum(s.qty) * 10
	else sum(s.qty) *5
end as zomato_points
from sales as s join products as p on s.products_id = p.products_id
group by 1,2
order by 2 desc;


select * from zomato_points;
-- Zomato points have been collected so far by individual user
select user_id ,sum(zomato_points) as total_points from zomato_points group by user_id order by 2 desc;

--  which  zomato product points rewarded to customers maximum

select product_name,sum(zomato_points) as total_points,round(sum(zomato_points)/5,0) as rewards_amount 
from zomato_points group by 1 order by 2 desc,3 desc;

select * from sales


/* Q16) Find top selling month of each year ? */
select * from (
select s.year,
       s.month_name ,
	   sum(s.qty * p.price_i) as total_sell,
	   row_number() over (
	                partition by s.year 
					order by sum(s.qty * p.price_i) desc 
					) as rnk 
from sales as s 
join products as p 
     on s.products_id=p.products_id 
group by 1,2 ) t 
where rnk=1;

/* Q17) see the sell difference of each month with previous month ? */

select s.year,
       s.month_name,
	   s.month,
	   sum(s.qty * p.price_i) as total_sell,
	   lag(sum(s.qty * p.price_i)) over (
	                partition by s.year 
					order by s.month asc 
					) as previous_month_sell ,
		sum(s.qty * p.price_i) - lag(sum(s.qty * p.price_i)) over (partition by s.year order by s.month asc ) as Difference 
from sales as s 
join products as p 
     on s.products_id=p.products_id 
group by 1,2,3;











